# Generated by Django 2.0.1 on 2018-02-20 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orderbook', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderbook',
            old_name='receipt',
            new_name='receipt_url',
        ),
    ]
