# Generated by Django 2.0.1 on 2018-02-08 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('thumbnail_url', models.TextField(blank=True, null=True)),
                ('orderd_page_url', models.TextField(blank=True, null=True)),
                ('book_url', models.TextField(blank=True, null=True)),
                ('type', models.IntegerField(choices=[(1, 'e-book'), (2, 'paper')], default=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
