# Generated by Django 2.0.1 on 2018-02-05 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webook', '0005_auto_20180125_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='type',
        ),
        migrations.AddField(
            model_name='books',
            name='book_type',
            field=models.IntegerField(choices=[(1, 'e-book'), (2, 'paper')], default=None),
        ),
        migrations.AlterField(
            model_name='books',
            name='book_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='orderd_page_url',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='thumbnail_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
